# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactionMechanism2' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactionMechanism2
  pod 'AAShareBubbles','~> 1.1'
  pod 'SCLAlertView-Objective-C', '~> 0.7.9'
  pod 'Google-Mobile-Ads-SDK'


  target 'ReactionMechanism2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactionMechanism2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
